CREATE TABLE `login` (
  `ID` VARCHAR(255) PRIMARY KEY,  
  `Username` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



